export type ListingCard = {
  id: string;
  ownerId: string;
  title: string;
  description?: string | null;
  purpose: 'SELL' | 'RENT';
  propertyCategory: 'HOME' | 'PLOT' | 'COMMERCIAL';
  propertySubtypeId: string;
  city: string;
  areaId: string;
  locationText: string;
  areaValue: number;
  areaUnit: 'MARLA' | 'SQFT' | 'SQYD' | 'KANAL';
  areaSqft: number;
  priceAmount: number;
  currency: 'PKR';
  installmentAvailable: boolean;
  readyForPossession: boolean;
  bedroomsCount?: number | null;
  bathroomsCount?: number | null;
  imagesJson: string[];
  videoUrl?: string | null;
  platforms: string[];
  status: string;
  publishedAt?: number | null;
  createdAt: number;
};
