INSERT INTO "areas" ("city", "name", "country_code", "is_active") VALUES
  ('Karachi', 'DHA Phase 8', 'PK', true),
  ('Karachi', 'Shahra-e-Faisal', 'PK', true),
  ('Karachi', 'Al-Murtaza Commercial Area', 'PK', true),
  ('Karachi', 'Saeeda Residency', 'PK', true),
  ('Karachi', 'Bukhari Commercial Area', 'PK', true),
  ('Karachi', 'DHA Phase 6', 'PK', true),
  ('Karachi', 'Shaheed Millat Road', 'PK', true),
  ('Karachi', 'DHA Phase 2 Extension', 'PK', true),
  ('Karachi', 'Korangi Industrial Area', 'PK', true),
  ('Karachi', 'DHA Phase 7', 'PK', true),
  ('Karachi', 'North Town Residency', 'PK', true),
  ('Karachi', 'Zulfiqar Commercial Area', 'PK', true),
  ('Karachi', 'DHA Phase 5', 'PK', true),
  ('Karachi', 'Bahadurabad', 'PK', true),
  ('Karachi', 'Scheme 33', 'PK', true),
  ('Karachi', 'Surjani Town', 'PK', true),
  ('Karachi', 'Sindh Industrial Trading Estate (SITE)', 'PK', true),
  ('Karachi', 'I.I. Chundrigar Road', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar', 'PK', true),
  ('Karachi', 'Tariq Road', 'PK', true),
  ('Karachi', 'Clifton - Block 7', 'PK', true),
  ('Karachi', 'Saima Arabian Villas', 'PK', true),
  ('Karachi', 'Jami Commercial Area', 'PK', true),
  ('Karachi', 'DHA Phase 7 Extension', 'PK', true),
  ('Karachi', 'Badar Commercial Area', 'PK', true),
  ('Karachi', 'Naya Nazimabad', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal', 'PK', true),
  ('Karachi', 'North Karachi', 'PK', true),
  ('Karachi', 'DHA Phase 2', 'PK', true),
  ('Karachi', 'Clifton - Block 9', 'PK', true),
  ('Karachi', 'Clifton', 'PK', true),
  ('Karachi', 'Clifton - Block 4', 'PK', true),
  ('Karachi', 'Zamzama Commercial Area', 'PK', true),
  ('Karachi', 'Sehar Commercial Area', 'PK', true),
  ('Karachi', 'Sharfabad', 'PK', true),
  ('Karachi', 'Clifton - Block 5', 'PK', true),
  ('Karachi', 'PECHS Block 2', 'PK', true),
  ('Karachi', 'Khalid Bin Walid Road', 'PK', true),
  ('Karachi', 'Shahbaz Commercial Area', 'PK', true),
  ('Karachi', 'Rahat Commercial Area', 'PK', true),
  ('Karachi', 'Rashid Minhas Road', 'PK', true),
  ('Karachi', 'Gulshan-e-Maymar', 'PK', true),
  ('Karachi', 'Clifton - Block 2', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 10', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 13', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 13/C', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 3-A', 'PK', true),
  ('Karachi', 'North Nazimabad - Block I', 'PK', true),
  ('Karachi', 'Saddar Cooperative Market', 'PK', true),
  ('Karachi', 'Federal B Area', 'PK', true),
  ('Karachi', 'Port Qasim', 'PK', true),
  ('Karachi', 'DHA Phase 1', 'PK', true),
  ('Karachi', 'Ittehad Commercial Area', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 5', 'PK', true),
  ('Karachi', 'North Nazimabad - Block H', 'PK', true),
  ('Karachi', 'Nishat Commercial Area', 'PK', true),
  ('Karachi', 'Muslim Commercial Area', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 13-D2', 'PK', true),
  ('Karachi', 'Bin Qasim Trade Centre', 'PK', true),
  ('Karachi', 'Gulzar-e-Hijri', 'PK', true),
  ('Karachi', 'University Road', 'PK', true),
  ('Karachi', 'PECHS', 'PK', true),
  ('Karachi', 'Mohammad Ali Society', 'PK', true),
  ('Karachi', 'Orangi Town', 'PK', true),
  ('Karachi', 'Clifton - Block 1', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 7', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 19', 'PK', true),
  ('Karachi', 'North Nazimabad - Block L', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 10-A', 'PK', true),
  ('Karachi', 'Old Queens Road', 'PK', true),
  ('Karachi', 'Saddar', 'PK', true),
  ('Karachi', 'Clifton - Block 8', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 17', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal Town', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 2', 'PK', true),
  ('Karachi', 'Allahwala Town', 'PK', true),
  ('Karachi', 'Falaknaz Dreams', 'PK', true),
  ('Karachi', 'Mehran Town', 'PK', true),
  ('Karachi', 'Malir', 'PK', true),
  ('Karachi', 'Federal B Area - Block 9', 'PK', true),
  ('Karachi', 'Gulshan-e-Maymar - Sector R', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 18', 'PK', true),
  ('Karachi', 'Nazimabad 3', 'PK', true),
  ('Karachi', 'Tauheed Commercial Area', 'PK', true),
  ('Karachi', 'Korangi Creek Cantonment', 'PK', true),
  ('Karachi', 'Gulshan-e-Maymar - Sector X', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 20', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 13/D-1', 'PK', true),
  ('Karachi', 'North Karachi Industrial Area', 'PK', true),
  ('Karachi', 'Mehran Town Sector 6B', 'PK', true),
  ('Karachi', 'Allahwala Town - Sector 31-G', 'PK', true),
  ('Karachi', 'Korangi', 'PK', true),
  ('Karachi', 'Model Colony - Malir', 'PK', true),
  ('Karachi', 'Shahra-e-Qaideen', 'PK', true),
  ('Karachi', 'Gadap Town', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 11', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 14', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 6', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 10', 'PK', true),
  ('Karachi', 'Garden East', 'PK', true),
  ('Karachi', 'Korangi - Sector 24', 'PK', true),
  ('Karachi', 'North Nazimabad - Block F', 'PK', true),
  ('Karachi', 'North Nazimabad - Block G', 'PK', true),
  ('Karachi', 'North Karachi - Sector 11-C/1', 'PK', true),
  ('Karachi', 'Allama Iqbal Road', 'PK', true),
  ('Karachi', 'Khayaban-e-Ittehad Road', 'PK', true),
  ('Karachi', 'Korangi - Sector 7/A', 'PK', true),
  ('Karachi', 'New Chali', 'PK', true),
  ('Karachi', 'Mehran Town Sector 6F', 'PK', true),
  ('Karachi', 'RJ Shopping Mall', 'PK', true),
  ('Karachi', 'Karachi Export Processing Zone (KEPZ)', 'PK', true),
  ('Karachi', 'Saima Mall & Residency', 'PK', true),
  ('Karachi', 'North Nazimabad', 'PK', true),
  ('Karachi', 'Civil Lines', 'PK', true),
  ('Karachi', 'Amir Khusro', 'PK', true),
  ('Karachi', 'DHA Phase 5 Extension', 'PK', true),
  ('Karachi', 'Federal B Area - Block 15', 'PK', true),
  ('Karachi', 'Federal B Area - Block 16', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 1', 'PK', true),
  ('Karachi', 'Korangi - Sector 27', 'PK', true),
  ('Karachi', 'P & T Housing Society', 'PK', true),
  ('Karachi', 'North Karachi - Sector 11I', 'PK', true),
  ('Karachi', 'North Nazimabad - Block M', 'PK', true),
  ('Karachi', 'Bahria Town Karachi', 'PK', true),
  ('Karachi', 'Capital Cooperative Housing Society', 'PK', true),
  ('Karachi', 'Jinnah Avenue', 'PK', true),
  ('Karachi', 'Meerut Society', 'PK', true),
  ('Karachi', 'Karachi University Housing Society', 'PK', true),
  ('Karachi', 'Burnes Road', 'PK', true),
  ('Karachi', 'Jamaluddin Afghani Road', 'PK', true),
  ('Karachi', 'Wasi Country Park', 'PK', true),
  ('Karachi', 'Guru Mandir Chorangi', 'PK', true),
  ('Karachi', 'DHA City - Sector 14B', 'PK', true),
  ('Karachi', 'Malir Town Residency', 'PK', true),
  ('Karachi', 'KN Gohar Green City', 'PK', true),
  ('Karachi', 'SITE Phase 2', 'PK', true),
  ('Karachi', 'Mehran Town Sector 6G', 'PK', true),
  ('Karachi', 'Nazimabad', 'PK', true),
  ('Karachi', 'Super Highway', 'PK', true),
  ('Karachi', 'Zamzama', 'PK', true),
  ('Karachi', 'SMCHS - Sindhi Muslim Society', 'PK', true),
  ('Karachi', 'DHA Phase 4', 'PK', true),
  ('Karachi', 'Saba Commercial Area', 'PK', true),
  ('Karachi', 'DHA Phase 8 - Zone A', 'PK', true),
  ('Karachi', 'Federal B Area - Block 7', 'PK', true),
  ('Karachi', 'Federal B Area - Block 8', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 1', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 12', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 15', 'PK', true),
  ('Karachi', 'Saadi Town', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 4', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 7', 'PK', true),
  ('Karachi', 'PECHS Block 6', 'PK', true),
  ('Karachi', 'Korangi - Sector 15', 'PK', true),
  ('Karachi', 'Bhittai Colony', 'PK', true),
  ('Karachi', 'Nazimabad 1', 'PK', true),
  ('Karachi', 'North Nazimabad - Block A', 'PK', true),
  ('Karachi', 'North Nazimabad - Block B', 'PK', true),
  ('Karachi', 'North Nazimabad - Block J', 'PK', true),
  ('Karachi', 'Saddar Town', 'PK', true),
  ('Karachi', 'Bagh-e-Malir', 'PK', true),
  ('Karachi', 'North Nazimabad - Block R', 'PK', true),
  ('Karachi', 'Surjani Town - Sector 6B', 'PK', true),
  ('Karachi', 'Quetta Town - Sector 18-A', 'PK', true),
  ('Karachi', 'Saima Presidency', 'PK', true),
  ('Karachi', 'Diamond City', 'PK', true),
  ('Karachi', 'MT Khan Road', 'PK', true),
  ('Karachi', 'Omega Mall Airport', 'PK', true),
  ('Karachi', 'Naya Nazimabad - Block A', 'PK', true),
  ('Karachi', 'Burj Al-Jinnah', 'PK', true),
  ('Karachi', 'Old Sabzi Mandi', 'PK', true),
  ('Karachi', 'North Karachi - Sector 2', 'PK', true),
  ('Karachi', 'Zulekha Residency', 'PK', true),
  ('Karachi', 'Gulshan-e-Jamal', 'PK', true),
  ('Karachi', 'Dhoraji Colony', 'PK', true),
  ('Karachi', 'Tipu Sultan Road', 'PK', true),
  ('Karachi', 'M.A. Jinnah Road', 'PK', true),
  ('Karachi', 'Lalazar', 'PK', true),
  ('Karachi', 'Shah Faisal Colony', 'PK', true),
  ('Karachi', 'DHA Phase 8 Extension', 'PK', true),
  ('Karachi', 'Malir Cantonment', 'PK', true),
  ('Karachi', 'Federal B Area - Block 10', 'PK', true),
  ('Karachi', 'Federal B Area - Block 13', 'PK', true),
  ('Karachi', 'Federal B Area - Block 17', 'PK', true),
  ('Karachi', 'Gulshan-e-Maymar - Sector Z', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 4', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 16', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 11', 'PK', true),
  ('Karachi', 'New Town Police Lines', 'PK', true),
  ('Karachi', 'Akhtar Colony', 'PK', true),
  ('Karachi', 'North Karachi - Sector 11A', 'PK', true),
  ('Karachi', 'North Nazimabad - Block N', 'PK', true),
  ('Karachi', 'Bufferzone - Sector 15-A/1', 'PK', true),
  ('Karachi', 'SITE Phase 1', 'PK', true),
  ('Karachi', 'Bahria Town - Precinct 1', 'PK', true),
  ('Karachi', 'Bahria Town - Precinct 2', 'PK', true),
  ('Karachi', 'Rimjhim VIllas', 'PK', true),
  ('Karachi', 'Suparco Road', 'PK', true),
  ('Karachi', 'Emaar Reef Towers', 'PK', true),
  ('Karachi', 'Techno City', 'PK', true),
  ('Karachi', 'Kings Skyline', 'PK', true),
  ('Karachi', 'Serena Mobile Mall', 'PK', true),
  ('Karachi', 'Shahrah-e-Pakistan', 'PK', true),
  ('Karachi', 'Bahria Town - Jinnah Avenue', 'PK', true),
  ('Karachi', 'Pakistan Post Office Workers CHS', 'PK', true),
  ('Karachi', 'Chapal Sun City', 'PK', true),
  ('Karachi', 'Sector 31 - Punjabi Saudagar City Phase 2', 'PK', true),
  ('Karachi', 'Falaknaz Excellency', 'PK', true),
  ('Karachi', 'Sohni Serenity Executive Apartments', 'PK', true),
  ('Karachi', 'Bahria Town - Precinct 10-A', 'PK', true),
  ('Karachi', 'Zainab Luxuria', 'PK', true),
  ('Karachi', 'North Karachi - Sector 14A', 'PK', true),
  ('Karachi', 'AQ Bazar', 'PK', true),
  ('Karachi', 'Falaknaz Twin Tower', 'PK', true),
  ('Karachi', 'Bath Island', 'PK', true),
  ('Karachi', 'DHA Defence', 'PK', true),
  ('Karachi', 'Frere Town', 'PK', true),
  ('Karachi', 'Hussainabad', 'PK', true),
  ('Karachi', 'Jamshed Road', 'PK', true),
  ('Karachi', 'Mangopir', 'PK', true),
  ('Karachi', 'Manzoor Colony', 'PK', true),
  ('Karachi', 'Soldier Bazar', 'PK', true),
  ('Karachi', 'Abdullah Haroon Road', 'PK', true),
  ('Karachi', 'Landhi', 'PK', true),
  ('Karachi', 'National Highway', 'PK', true),
  ('Karachi', 'Shah Faisal Town', 'PK', true),
  ('Karachi', 'Baldia Town', 'PK', true),
  ('Karachi', 'Nagan Chowrangi', 'PK', true),
  ('Karachi', 'New Karachi', 'PK', true),
  ('Karachi', 'Garden City', 'PK', true),
  ('Karachi', 'PIDC', 'PK', true),
  ('Karachi', 'Shahra-e-Liaquat', 'PK', true),
  ('Karachi', 'Clifton - Block 3', 'PK', true),
  ('Karachi', 'Clifton - Block 6', 'PK', true),
  ('Karachi', 'Gulshan-e-Hadeed - Phase 1', 'PK', true),
  ('Karachi', 'Clifton Block 7 - Zone C', 'PK', true),
  ('Karachi', 'Delhi Colony', 'PK', true),
  ('Karachi', 'Federal B Area - Block 1', 'PK', true),
  ('Karachi', 'Federal B Area - Block 18', 'PK', true),
  ('Karachi', 'Federal B Area - Block 20', 'PK', true),
  ('Karachi', 'Surjani Town - Sector 2', 'PK', true),
  ('Karachi', 'Surjani Town - Sector 4A', 'PK', true),
  ('Karachi', 'Surjani Town - Sector 7A', 'PK', true),
  ('Karachi', 'Gulshan-e-Maymar - Sector W', 'PK', true),
  ('Karachi', 'Gulshan-e-Shameem', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 2', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 3', 'PK', true),
  ('Karachi', 'Essa Nagri', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 3', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 4A', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 8', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 14', 'PK', true),
  ('Karachi', 'Gulshan-e-Kaneez Fatima', 'PK', true),
  ('Karachi', 'Patel Para', 'PK', true),
  ('Karachi', 'Maripur', 'PK', true),
  ('Karachi', 'Korangi - Sector 7', 'PK', true),
  ('Karachi', 'Korangi - Sector 30', 'PK', true),
  ('Karachi', 'Korangi - Sector 33/D', 'PK', true),
  ('Karachi', 'Darusslam Society', 'PK', true),
  ('Karachi', 'Nazimabad 2', 'PK', true),
  ('Karachi', 'Nazimabad 5', 'PK', true),
  ('Karachi', 'Jaffar-e-Tayyar', 'PK', true),
  ('Karachi', 'Godhra', 'PK', true),
  ('Karachi', 'North Karachi - Sector 11E', 'PK', true),
  ('Karachi', 'North Karachi - Sector 11L', 'PK', true),
  ('Karachi', 'Paposh Nagar', 'PK', true),
  ('Karachi', 'North Nazimabad - Block D', 'PK', true),
  ('Karachi', 'Qayyumabad', 'PK', true),
  ('Karachi', 'Gulshan-e-Rafi', 'PK', true),
  ('Karachi', 'Defence View Society', 'PK', true),
  ('Karachi', 'Defence View Phase 1', 'PK', true),
  ('Karachi', 'Defence View Phase 2', 'PK', true),
  ('Karachi', 'Federal B Area - Block 22', 'PK', true),
  ('Karachi', 'DHA City - Sector 3', 'PK', true),
  ('Karachi', 'DHA City - Sector 14', 'PK', true),
  ('Karachi', 'Gulshan-e-Hadeed Phase 2 Extension', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 13/A', 'PK', true),
  ('Karachi', '10th Commercial Street - DHA Phase 4', 'PK', true),
  ('Karachi', 'Stadium Commercial Area', 'PK', true),
  ('Karachi', 'Kings Luxury Apartments', 'PK', true),
  ('Karachi', 'Gulshan-e-Iqbal - Block 13/B', 'PK', true),
  ('Karachi', 'Gulistan-e-Jauhar - Block 16-A', 'PK', true),
  ('Karachi', 'Stadium Road', 'PK', true),
  ('Karachi', 'Bufferzone - Sector 15-A/5', 'PK', true),
  ('Karachi', 'Baloch Colony', 'PK', true),
  ('Karachi', 'Surjani Town - Sector 11A', 'PK', true),
  ('Karachi', 'Gwalior Cooperative Housing Society', 'PK', true),
  ('Karachi', 'Pakistan Merchant Navy Society', 'PK', true),
  ('Karachi', 'Pakistan Air Crew Cooperative Housing Society', 'PK', true),
  ('Karachi', 'Etawa Society', 'PK', true),
  ('Karachi', 'Government Teacher Housing Society - Sector 16-A', 'PK', true),
  ('Karachi', 'Hub River Road', 'PK', true),
  ('Karachi', 'Aisha Manzil', 'PK', true),
  ('Karachi', 'Gizri Road', 'PK', true),
  ('Karachi', 'Abul Hassan Isphani Road', 'PK', true),
  ('Karachi', 'Falcon Complex New Malir', 'PK', true),
  ('Karachi', 'Millat Garden', 'PK', true),
  ('Karachi', 'Alamgir Road', 'PK', true),
  ('Karachi', 'Falaknaz Presidency', 'PK', true),
  ('Karachi', 'Bahria Town - Precinct 4', 'PK', true),
  ('Karachi', 'Bahria Town - Precinct 17', 'PK', true),
  ('Karachi', 'Shaheed-e-Millat Expressway', 'PK', true),
  ('Karachi', 'Safoora Goth', 'PK', true),
  ('Karachi', 'Al-Muslim Cooperative Housing Society Phase 2', 'PK', true),
  ('Karachi', 'City Tower And Shopping Mall', 'PK', true),
  ('Karachi', 'Noman Residencia', 'PK', true),
  ('Karachi', 'Saadabad Cooperative Housing Society', 'PK', true),
  ('Karachi', 'Shamim Sky Line', 'PK', true),
  ('Karachi', 'Pak Ideal Cooperative Housing Society', 'PK', true),
  ('Karachi', 'Bahria Midway Commercial', 'PK', true),
  ('Karachi', 'Federal Government Employees Housing Foundation', 'PK', true),
  ('Karachi', 'Azam Town', 'PK', true),
  ('Karachi', 'Tulip Tower', 'PK', true),
  ('Karachi', 'Rainbow Towers And Shopping Mall', 'PK', true),
  ('Karachi', 'Kashmir Colony', 'PK', true),
  ('Karachi', 'Safari Enclave Apartments', 'PK', true),
  ('Karachi', 'Sohni Golf View Apartments', 'PK', true),
  ('Karachi', 'Sanober Twin Tower', 'PK', true),
  ('Karachi', 'North Karachi - Sector 12-C', 'PK', true),
  ('Karachi', 'Jauhar Chowrangi Road', 'PK', true),
  ('Karachi', 'Ranchore Line Bazar', 'PK', true),
  ('Karachi', 'Maskan Chowrangi', 'PK', true),
  ('Karachi', 'Amil Colony', 'PK', true),
  ('Karachi', 'Surjani Town - Sector 5E', 'PK', true),
  ('Karachi', 'North Karachi - Sector 5M', 'PK', true),
  ('Karachi', 'Al-Hilal Society', 'PK', true),
  ('Karachi', 'LaCasaOne', 'PK', true),
  ('Karachi', 'Brookes Chowrangi', 'PK', true),
  ('Karachi', 'Police Society', 'PK', true),
  ('Karachi', 'Korangi - Sector 31-A', 'PK', true),
  ('Karachi', 'Metroville 3', 'PK', true),
  ('Karachi', 'Sumaira Bungalows', 'PK', true),
  ('Karachi', 'Dominion Business Center', 'PK', true),
  ('Karachi', 'Saadi Town - Block 2', 'PK', true),
  ('Karachi', 'KDA Employees Society - Korangi', 'PK', true),
  ('Karachi', 'KDA Employees Society - Sector 31-C2', 'PK', true),
  ('Karachi', 'Pir Ahmed Zaman Town - Block 3', 'PK', true),
  ('Karachi', 'Scheme 33 - Sector 31', 'PK', true),
  ('Karachi', 'Sector 32 - Punjabi Saudagar City Phase 1', 'PK', true),
  ('Karachi', 'Dominion Business Center 2', 'PK', true),
  ('Karachi', 'Liaquatabad - Block 3', 'PK', true),
  ('Karachi', 'Liaquatabad - Block 4', 'PK', true),
  ('Karachi', 'Jinnah Trade Center', 'PK', true),
  ('Karachi', 'Andaleeb Cooperative Housing Society', 'PK', true),
  ('Karachi', 'Gulshan-e-Kaneez Fatima - Block 1', 'PK', true),
  ('Karachi', 'Gulshan-e-Kaneez Fatima - Block 2', 'PK', true),
  ('Karachi', 'Country Terrace', 'PK', true),
  ('Karachi', 'Metrovil Colony - Block 3/2', 'PK', true),
  ('Karachi', 'Naya Nazimabad - Block B', 'PK', true),
  ('Karachi', 'Muhammad Ali Shaheed Society', 'PK', true),
  ('Karachi', 'Lateef Duplex Luxuria', 'PK', true),
  ('Karachi', 'Liaqat Market', 'PK', true),
  ('Karachi', 'Emaar Panorama', 'PK', true),
  ('Karachi', 'DHA Phase 2 - A Commercial Area', 'PK', true),
  ('Karachi', 'Hyderi', 'PK', true),
  ('Karachi', 'Nazimabad 3 - Block B', 'PK', true),
  ('Karachi', 'Nazimabad 1 - Block A', 'PK', true),
  ('Karachi', 'Faisal Commercial Area', 'PK', true),
  ('Karachi', 'Mehran Town Extension Sector 30', 'PK', true),
  ('Karachi', 'Bhittai Colony - Block C', 'PK', true),
  ('Karachi', 'North Karachi - Sector 7-D4', 'PK', true),
  ('Karachi', 'HMR Waterfront', 'PK', true),
  ('Karachi', 'Falak Corporate City', 'PK', true),
  ('Karachi', 'Dominion Shopping Mall', 'PK', true),
  ('Karachi', 'KAECHS - Block 4', 'PK', true),
  ('Karachi', 'KAECHS - Block 3', 'PK', true),
  ('Karachi', 'Malir Town Residency - Phase 6', 'PK', true),
  ('Karachi', 'Dolce Mall & Signature Residency', 'PK', true),
  ('Karachi', 'Malir Town Residency - Phase 2', 'PK', true),
  ('Karachi', 'Khayaban-e-Shahbaz', 'PK', true),
  ('Karachi', 'Al Ghafoor Grande City', 'PK', true),
  ('Karachi', 'Rashidi Goth', 'PK', true),
  ('Karachi', 'Jakvani Shopping Center', 'PK', true),
  ('Karachi', 'Sawera Enclave', 'PK', true),
  ('Karachi', 'Millennium Mall', 'PK', true),
  ('Karachi', 'AQ Super Market', 'PK', true),
  ('Karachi', 'Korangi - Sector 5', 'PK', true),
  ('Karachi', 'Rim Jhim Towers', 'PK', true),
  ('Karachi', 'Milat Corner', 'PK', true),
  ('Karachi', 'Nad e Ali Road', 'PK', true),
  ('Karachi', 'Gevora Hills', 'PK', true)
ON CONFLICT ("city", "name") DO NOTHING;
